DROP DATABASE IF EXISTS blamazon;
CREATE DATABASE blamazon;

USE blamazon;

CREATE TABLE PRODUCTS (
    ITEM_ID INT NOT NULL AUTO_INCREMENT,
    PRODUCT_NAME VARCHAR(50) NOT NULL,
    DEPT_NAME VARCHAR(30) NOT NULL,
    PRICE DECIMAL(4,2) NULL,
    STOCK_QUANITY INT(3) NULL,
    PRIMARY KEY (ITEM_ID)
);